// value 值来源与 iconfont.js 与 icomoon.js 中
export const groupList = [
  { code: 'all', label: '全部' },
  { code: 'dodaf', label: 'DoDaf' },
]

export const svgList = [
  {
    key: 'VP-AV',
    value: 'icon-dodaf-vp-av',
    label: 'AV',
    group: 'dodaf',
  },

  {
    key: 'VP-CV',
    value: 'icon-dodaf-vp-cv',
    label: 'CV',
    group: 'dodaf',
  },
  {
    key: 'VP-OV',
    value: 'icon-dodaf-vp-ov',
    label: 'OV',
    group: 'dodaf',
  },
  {
    key: 'VP-SV',
    value: 'icon-dodaf-vp-sv',
    label: 'SV',
    group: 'dodaf',
  },
  {
    key: 'VP-SVCV',
    value: 'icon-dodaf-vp-svcv',
    label: 'VP-SVCV',
    group: 'dodaf',
  },
  {
    key: 'VP-DIV',
    value: 'icon-dodaf-vp-div',
    label: 'DIV',
    group: 'dodaf',
  },
  {
    key: 'VP-TV',
    value: 'icon-dodaf-vp-tv',
    label: 'TV',
    group: 'dodaf',
  },
  {
    key: 'VP-PV',
    value: 'icon-dodaf-vp-pv',
    label: 'PV',
    group: 'dodaf',
  },
  {
    key: 'AV1',
    value: 'icon-AV1',
    label: 'AV1',
    group: 'dodaf',
  },
  {
    key: 'AV1',
    value: 'icon-AV1',
    label: 'AV1',
    group: 'dodaf',
  },
  {
    key: 'AV1',
    value: 'icon-AV1',
    label: 'AV1',
    group: 'dodaf',
  },
  {
    key: 'AV1',
    value: 'icon-AV1',
    label: 'AV1',
    group: 'dodaf',
  },
  {
    key: 'AV1',
    value: 'icon-AV1',
    label: 'AV1',
    group: 'dodaf',
  },
  {
    key: 'AV2',
    value: 'icon-AV2',
    label: 'AV2',
    group: 'dodaf',
  },
  {
    key: 'AV3',
    value: 'icon-AV3',
    label: 'AV3',
    group: 'dodaf',
  },
  {
    key: 'CV1',
    value: 'icon-CV1',
    label: 'CV1',
    group: 'dodaf',
  },
  {
    key: 'CV2',
    value: 'icon-CV2',
    label: 'CV2',
    group: 'dodaf',
  },
  {
    key: 'CV3',
    value: 'icon-CV3',
    label: 'CV3',
    group: 'dodaf',
  },
  {
    key: 'CV4',
    value: 'icon-CV4',
    label: 'CV4',
    group: 'dodaf',
  },
  {
    key: 'CV6',
    value: 'icon-CV6',
    label: 'CV6',
    group: 'dodaf',
  },
  {
    key: 'CV7',
    value: 'icon-CV7',
    label: 'CV7',
    group: 'dodaf',
  },
  {
    key: 'CV8',
    value: 'icon-CV8',
    label: 'CV8',
    group: 'dodaf',
  },
  {
    key: 'DIV1',
    value: 'icon-DIV1',
    label: 'DIV1',
    group: 'dodaf',
  },
  {
    key: 'DIV2',
    value: 'icon-DIV2',
    label: 'DIV2',
    group: 'dodaf',
  },
  {
    key: 'DIV3',
    value: 'icon-DIV3',
    label: 'DIV3',
    group: 'dodaf',
  },
  {
    key: 'OV1',
    value: 'icon-OV1',
    label: 'OV1',
    group: 'dodaf',
  },
  {
    key: 'OV2',
    value: 'icon-OV2',
    label: 'OV2',
    group: 'dodaf',
  },
  {
    key: 'OV3',
    value: 'icon-OV3',
    label: 'OV3',
    group: 'dodaf',
  },
  {
    key: 'OV4',
    value: 'icon-OV4',
    label: 'OV4',
    group: 'dodaf',
  },
  {
    key: 'OV5',
    value: 'icon-OV5',
    label: 'OV5',
    group: 'dodaf',
  },
  {
    key: 'OV5a',
    value: 'icon-OV5a',
    label: 'OV5a',
    group: 'dodaf',
  },
  {
    key: 'OV5b',
    value: 'icon-OV5b',
    label: 'OV5b',
    group: 'dodaf',
  },
  {
    key: 'OV6',
    value: 'icon-OV6',
    label: 'OV6',
    group: 'dodaf',
  },
  {
    key: 'OV6a',
    value: 'icon-OV6a',
    label: 'OV6a',
    group: 'dodaf',
  },
  {
    key: 'OV6b',
    value: 'icon-OV6b',
    label: 'OV6b',
    group: 'dodaf',
  },
  {
    key: 'OV6c',
    value: 'icon-OV6c',
    label: 'OV6c',
    group: 'dodaf',
  },
  {
    key: 'SV6',
    value: 'icon-SV6',
    label: 'SV6',
    group: 'dodaf',
  },
  {
    key: 'SV7',
    value: 'icon-SV7',
    label: 'SV7',
    group: 'dodaf',
  },
  {
    key: 'SV9',
    value: 'icon-SV9',
    label: 'SV9',
    group: 'dodaf',
  },
  {
    key: 'SV4',
    value: 'icon-SV4',
    label: 'SV4',
    group: 'dodaf',
  },
  {
    key: 'SV10b',
    value: 'icon-SV10b',
    label: 'SV10b',
    group: 'dodaf',
  },
  {
    key: 'SV10',
    value: 'icon-SV10',
    label: 'SV10',
    group: 'dodaf',
  },
  {
    key: 'SV10a',
    value: 'icon-SV10a',
    label: 'SV10a',
    group: 'dodaf',
  },
  {
    key: 'SV10c',
    value: 'icon-SV10c',
    label: 'SV10c',
    group: 'dodaf',
  },
  {
    key: 'SvcV4',
    value: 'icon-SvcV4',
    label: 'SvcV4',
    group: 'dodaf',
  },
  {
    key: 'SvcV5',
    value: 'icon-SvcV5',
    label: 'SvcV5',
    group: 'dodaf',
  },
  {
    key: 'SvcV3',
    value: 'icon-SvcV3',
    label: 'SvcV3',
    group: 'dodaf',
  },
  {
    key: 'SvcV1',
    value: 'icon-SvcV1',
    label: 'SvcV1',
    group: 'dodaf',
  },
  {
    key: 'SvcV7',
    value: 'icon-SvcV7',
    label: 'SvcV7',
    group: 'dodaf',
  },
  {
    key: 'SvcV9',
    value: 'icon-SvcV9',
    label: 'SvcV9',
    group: 'dodaf',
  },
  {
    key: 'SvcV2',
    value: 'icon-SvcV2',
    label: 'SvcV2',
    group: 'dodaf',
  },
  {
    key: 'SvcV10c',
    value: 'icon-SvcV10c',
    label: 'SvcV10c',
    group: 'dodaf',
  },
  {
    key: 'SvcV8',
    value: 'icon-SvcV8',
    label: 'SvcV8',
    group: 'dodaf',
  },
  {
    key: 'SvcV3a',
    value: 'icon-SvcV3a',
    label: 'SvcV3a',
    group: 'dodaf',
  },
  {
    key: 'SvcV10a',
    value: 'icon-SvcV10a',
    label: 'SvcV10a',
    group: 'dodaf',
  },
  {
    key: 'SvcV6',
    value: 'icon-SvcV6',
    label: 'SvcV6',
    group: 'dodaf',
  },
  {
    key: 'SvcV3b',
    value: 'icon-SvcV3b',
    label: 'SvcV3b',
    group: 'dodaf',
  },
  {
    key: 'SvcV10b',
    value: 'icon-SvcV10b',
    label: 'SvcV10b',
    group: 'dodaf',
  },
  {
    key: 'SvcV10',
    value: 'icon-SvcV10',
    label: 'SvcV10',
    group: 'dodaf',
  },
  {
    key: 'SV2',
    value: 'icon-SV2',
    label: 'SV2',
    group: 'dodaf',
  },
  {
    key: 'SV2a',
    value: 'icon-SV2a',
    label: 'SV2a',
    group: 'dodaf',
  },
  {
    key: 'SV1a',
    value: 'icon-SV1a',
    label: 'SV1a',
    group: 'dodaf',
  },
  {
    key: 'SV1',
    value: 'icon-SV1',
    label: 'SV1',
    group: 'dodaf',
  },
  {
    key: 'SV1b',
    value: 'icon-SV1b',
    label: 'SV1b',
    group: 'dodaf',
  },
  {
    key: 'SV2b',
    value: 'icon-SV2b',
    label: 'SV2b',
    group: 'dodaf',
  },
  {
    key: 'SV3',
    value: 'icon-SV3',
    label: 'SV3',
    group: 'dodaf',
  },
  {
    key: 'SV5a',
    value: 'icon-SV5a',
    label: 'SV5a',
    group: 'dodaf',
  },
  {
    key: 'SV5',
    value: 'icon-SV5',
    label: 'SV5',
    group: 'dodaf',
  },
  {
    key: 'SV4b',
    value: 'icon-SV4b',
    label: 'SV4b',
    group: 'dodaf',
  },
  {
    key: 'SV5b',
    value: 'icon-SV5b',
    label: 'SV5b',
    group: 'dodaf',
  },
  {
    key: 'SV8',
    value: 'icon-SV8',
    label: 'SV8',
    group: 'dodaf',
  },
  {
    key: 'SV4a',
    value: 'icon-SV4a',
    label: 'SV4a',
    group: 'dodaf',
  },
  {
    key: 'SV3b',
    value: 'icon-SV3b',
    label: 'SV3b',
    group: 'dodaf',
  },
  {
    key: 'SV3a',
    value: 'icon-SV3a',
    label: 'SV3a',
    group: 'dodaf',
  },
  {
    key: 'TV1',
    value: 'icon-TV1',
    label: 'TV1',
    group: 'dodaf',
  },
  {
    key: 'TV2',
    value: 'icon-TV2',
    label: 'TV2',
    group: 'dodaf',
  },
  {
    key: 'PV1',
    value: 'icon-PV1',
    label: 'PV1',
    group: 'dodaf',
  },
  {
    key: 'PV2',
    value: 'icon-PV2',
    label: 'PV2',
    group: 'dodaf',
  },
  {
    key: 'PV3',
    value: 'icon-PV3',
    label: 'PV3',
    group: 'dodaf',
  },
]
